version: '3'

services:
  achfl-server:
     image: php:8.1-apache
     container_name: achfl-server
     ports:
       - "80:80"
     volumes:
       - ./logs:/var/log/apache2/
       - ../:/var/www/html/ 
     restart: always
     tty: true
     stdin_open: true